vich_uploader:
    db_driver: orm

    mappings:
        rondoneimage:
            uri_prefix: /images/rondonne
            upload_destination: '%kernel.project_dir%/public/Upload/'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true